// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/AlemayehuDabi/Smart_Sheild/services/trading-engine/internal/auth/model"

)

type AuthPayload struct {
	Token string    `json:"token"`
	User  *AuthUser `json:"user"`
}

type AuthUser struct {
	ID    string  `json:"id"`
	Email string  `json:"email"`
	Name  *string `json:"name,omitempty"`
	Role  string  `json:"role"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
