package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"

	authctx "github.com/AlemayehuDabi/Smart_Sheild/services/trading-engine/internal/auth/ctx"
	"github.com/AlemayehuDabi/Smart_Sheild/services/trading-engine/internal/auth/dto"
	"github.com/AlemayehuDabi/Smart_Sheild/services/trading-engine/internal/graphql/model"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	if r.UserService == nil {
		return nil, errors.New("authentication service unavailable")
	}
	out, err := r.UserService.Register(dto.RegisterInput{
		Name:     input.Name,
		Email:    input.Email,
		Password: input.Password,
	})
	if err != nil {
		return nil, err
	}
	return authPayloadToModel(out), nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	if r.UserService == nil {
		return nil, errors.New("authentication service unavailable")
	}
	out, err := r.UserService.Login(dto.LoginInput{
		Email:    input.Email,
		Password: input.Password,
	})
	if err != nil {
		return nil, err
	}
	return authPayloadToModel(out), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.AuthUser, error) {
	if r.UserService == nil {
		return nil, errors.New("authentication service unavailable")
	}
	uid, ok := authctx.UserID(ctx)
	if !ok {
		return nil, nil
	}
	u, err := r.UserService.GetUserProfile(uid)
	if err != nil {
		return nil, err
	}
	return domainUserToGraphQL(u), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
